package net.ages.alwb.gateway.utils.enums;

public enum ALERTS {
	ABOUT
	, ERROR_UTILS_MESSAGES
	, MISSING_DOMAIN
	, MISSING_HTML
	, MISSING_MATINS_COMMON
	, MISSING_SERVER
	, MISSING_USER_ACCOUNT
	, NO_SYNCH_PREF_SELECTED
	, NOT_AUTHENTICATED
	, OK_TO_SYNCH
	, SERVER_NOT_AVAILABLE
}
